# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cinemaratona
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  cinemaratona:
    image: cinemaratona
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5199:5199
    depends_on:
      postgres:
        condition: service_healthy
    environment:
    - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=cinemaratona;Username=postgres;Password=postgres

volumes:
  postgres-data:
